### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Find transparent bg image for car, and background color.
- [x] Make basic html page showing the car sized appropriately.
- [x] Remove excess code.

**Comment by gavenlou** [comment]
<a href="https://gyazo.com/dbcfd1363504be1f7b99eeab554ee2bd"><img src="https://i.gyazo.com/dbcfd1363504be1f7b99eeab554ee2bd.png" alt="Image from Gyazo" width="550.4"/></a>
