### ISSUE TITLE
User can pick up Coins/Nitro

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/driving-game#11]
## 💰 Motivation
Who doesn't love snake?

## 📐 Plan
Add random coin pickups/coin counter, and a nitro pick up.

## ✅ Task List

- [x] Add a new coin/nitro object. 
- [x] Add a coin counter. (sound effects? strong maybe)
- [x] Add randomized coordinates to new objects at start.
- [x] Change pick-up location when car coordinates are near.
- [ ] Make nitro temporarily increase speed.
- [ ] Make sure it works.
- [ ] Remove excess code.
