### ISSUE TITLE
User can change their Car color/ map background.

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/driving-game#12]
## 💰 Motivation
Sometimes red is a poor choice and green is overused.

## 📐 Plan
Add buttons to change car image and body background colors.

## ✅ Task List

- [ ] Add navbar with list of different images/ background colors.
- [ ] Lower car starting point so it doesn't clip the navbar. (Alt: put bar on the side)
- [ ] Add functions to change either the car or background.
- [ ] Make sure they don't look really bad when you rotate them. Maybe disable transform on certain cars.
- [ ] Remove excess code.
