### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add CSS classes that rotate the car when applied.
- [x] Add data-model containing the car's direction.
- [x] Add event listeners to arrow keys to change CSS classes and data-direction.
- [x] Remove excess code.
