### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add coordinates to data-model.
- [x] Use absolute positioning for car placement.
- [x] Move car with style left/top offset.
- [x] Move car every 16ms.
- [x] Add event listener to 'space' key for movement updates.
- [x] Remove excess code.
