### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Change x/y coordinates based off of data-direction and update style accordingly.
- [x] Make sure it actually works and has fluid movement.
- [x] Remove excess code.
